# Generated by Django 2.2.7 on 2020-10-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=64)),
                ('studentage', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('password', models.IntegerField()),
                ('studentaddress', models.CharField(max_length=64)),
            ],
        ),
    ]
